x-db-connection: &db-connection
  POSTGRES_DB: core
  POSTGRES_USER: core
  POSTGRES_PASSWORD: core

services:
  database:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment: *db-connection
    volumes:
      - alchemy_data:/var/lib/postgresql/data


  api:
    profiles:
      - dev
    build:
      context: .
      target: dev-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      CORE__SQLALCHEMY_URI: "postgresql+asyncpg://core:core@database:5432/core"
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./src:/usr/src/api/src

volumes:
  alchemy_data:
