"""init

Revision ID: 2d79417fccdc
Revises:
Create Date: 2024-04-13 13:57:34.069135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d79417fccdc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_author")),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
    )
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "publication_type",
            sa.Enum("MAGAZINE", "BOOK", name="publicationtype"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["author.id"], name=op.f("fk_book_author_id_author")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["publication.id"], name=op.f("fk_book_id_publication")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
    )
    op.create_table(
        "category__publication",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_category__publication_category_id_category"),
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publication.id"],
            name=op.f("fk_category__publication_publication_id_publication"),
        ),
        sa.PrimaryKeyConstraint(
            "publication_id", "category_id", name=op.f("pk_category__publication")
        ),
    )
    op.create_table(
        "favorite_publications",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publication.id"],
            name=op.f("fk_favorite_publications_publication_id_publication"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_favorite_publications_user_id_user")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "publication_id", name=op.f("pk_favorite_publications")
        ),
    )
    op.create_table(
        "magazine",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["publication.id"], name=op.f("fk_magazine_id_publication")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_magazine")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("magazine")
    op.drop_table("favorite_publications")
    op.drop_table("category__publication")
    op.drop_table("book")
    op.drop_table("user")
    op.drop_table("publication")
    op.drop_table("category")
    op.drop_table("author")
    op.execute("DROP TYPE publicationtype;")
    # ### end Alembic commands ###
